# Generated by Django 3.2.3 on 2021-06-25 00:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='not_dead_tomorrow',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='born_before_today',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_death__lte', datetime.date(2021, 6, 26))), name='not_dead_tomorrow'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_of_birth__lte', datetime.date(2021, 6, 25))), name='born_before_today'),
        ),
    ]
