# Generated by Django 3.2.3 on 2021-06-21 01:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="not_dead_tomorrow",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="born_before_today",
        ),
        migrations.AlterField(
            model_name="user",
            name="honorific_prefix",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mr", "Single or Married Man"),
                    ("Mrs", "Married Woman"),
                    ("Ms", "Single or Married Woman"),
                    ("Dr", "Medical Doctor"),
                    (
                        "Hon",
                        "Honorable (Judge, Justice, other High Ranking Gov official",
                    ),
                    ("Eld", "Elder (religious title)"),
                    ("Fth", "Father (religious title)"),
                    ("Bth", "Brother (religious title)"),
                    ("Sis", "Sister (nun or other female religious leader)"),
                    ("Rev", "Reverand (Religious leader"),
                    ("Rab", "Rabbi (religious leader usually of jewish faith)"),
                ],
                default="",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="honorific_suffix",
            field=models.CharField(
                blank=True,
                choices=[("PhD", "Doctoralily Educated"), ("Esq", "Esquire, Lawyer")],
                default="",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_death__lte", datetime.date(2021, 6, 22))),
                name="not_dead_tomorrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_birth__lte", datetime.date(2021, 6, 21))),
                name="born_before_today",
            ),
        ),
    ]
