# Generated by Django 3.2.4 on 2021-06-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210621_0142'),
        ('users', '0002_auto_20210621_1736'),
    ]

    operations = [
    ]
