# Generated by Django 3.2.4 on 2021-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210703_1626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_state",
            field=models.CharField(max_length=2),
        ),
    ]
