# Generated by Django 3.2.3 on 2021-06-30 11:48

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_address_state"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="not_dead_tomorrow",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="born_before_today",
        ),
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAIL", "Mailing"),
                    ("RESD", "Residential"),
                    ("BUSN", "Business"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_death__lte", datetime.date(2021, 7, 1))),
                name="not_dead_tomorrow",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("date_of_birth__lte", datetime.date(2021, 6, 30))),
                name="born_before_today",
            ),
        ),
    ]
