# Generated by Django 3.2 on 2021-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "base_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("role_name", models.CharField(blank=True, max_length=100, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FT", "Full-time Position"),
                            ("PT", "Part-time Position"),
                            ("CT", "Contract Position"),
                            ("TP", "Temporary Position"),
                            ("SN", "Seasonal Position"),
                            ("IN", "Internship Position"),
                            ("AP", "Apprenticeship Position"),
                        ],
                        default="FT",
                        max_length=2,
                    ),
                ),
                (
                    "employer_overview",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "experience_requirements",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
