# Generated by Django 3.2 on 2021-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="remote_position",
            field=models.BooleanField(default=True),
        ),
    ]
