# Generated by Django 3.2 on 2021-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_experience_preferred"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="lead",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("APP", "Applied for position"),
                    ("INT", "Interview with organization"),
                    ("ACT", "Offer Extended, Accepted"),
                    ("DCL", "Offer Extended, Voluntarily withdrawl"),
                    ("WDW", "Voluntary Candidancy Withdrawl"),
                    ("DNY", "Involuntary Candidancy Withdrawl"),
                ],
                default="APP",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="application_submission",
            field=models.FileField(
                default="", upload_to="employment/job_applications/%Y/%m/%d/"
            ),
        ),
    ]
