# Generated by Django 3.2 on 2021-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_auto_20210504_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
