# pyproject.toml

# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.

#==========================================================================================
# PYTEST - TESTING FRAMEWORK
#==========================================================================================
[tool.pytest.ini_options]
automock_unlocked=true
DJANGO_SETTINGS_MODULE = "halfwitter.settings"
minversion = "6.0"
addopts = "-ra -vv --disable-warnings"
python_files = [
  "test.py",
  "tests.py",
  "test_*.py",
  "*_test.py",
  "check_*.py",
  "*_check.py",
  "example_*.py",
  "*_example.py",
]
python_functions = [
  "suite_*",
  "*_suite",
  "test_*",
  "*_test",
  "check_*",
  "*_check",
  "example_*",
  "*_example",
]
python_classes = [
  "Test*",
  "*Test",
  "Check*",
  "Suite*",
  "*Suite",
  "*Check",
  "Example*",
  "*Example",
]
filterwarnings = [
  "error",
  "ignore::UserWarning",
  # note the use of single quote below to denote "raw" strings in TOML
  'ignore:function ham\(\) is deprecated:DeprecationWarning',
]
#testpaths = ["tests"]
#==========================================================================================
# BLACK - PYTHON FORMATTING TOOL
#==========================================================================================
[tool.black]
line-length = 88
target-version = ['py36','py37', 'py38',]
