# Generated by Django 3.2.4 on 2021-07-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_modified",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
