# Generated by Django 3.2.4 on 2021-07-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20210703_1613"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date_expired",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
