# Generated by Django 3.2.4 on 2021-07-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_date_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="publication_type",
            field=models.CharField(
                choices=[
                    ("ANNCMNT", "Public Announcement"),
                    ("CONCMNT", "Private Post"),
                ],
                default="CONCMNT",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="date_expired",
            field=models.DateField(blank=True, null=True),
        ),
    ]
