# Generated by Django 3.2.4 on 2021-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20210706_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
